- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: Install python nodejs and npm
  apt:
    pkg:
      - python3-pip

- name: Install NVM
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Install node and set version
  become: yes
  become_user: root
  shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install 13.8.0" 
  args:
    executable: /bin/bash

- name: Install NPM
  become: yes
  apt:
    pkg:
      - npm
    
- name: Install pm2
  become: yes
  command:
    cmd: npm install pm2@latest -g
