- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: Install python and pip
  apt:
    pkg:
      - python3-pip

- name: Install NVM
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  args:
    executable: /bin/bash
    chdir: /home/ubuntu
    creates: "/home/ubuntu/.nvm/nvm.sh"

- name: Install node and set version
  become: yes
  shell: "source /home/ubuntu/.nvm/nvm.sh && nvm install 13.8.0" 
  args:
    executable: /bin/bash

- name: Install NPM
  become: yes
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes
    
- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
