- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: Install python nodejs and npm
  apt:
    pkg:
      - python3-pip

- name: Install NVM
  become: yes
  shell: |
    wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

- name: Install Nodejs using NVM
  become: yes
  shell: |
    nvm install 13.8.0

- name: Install NPM
  become: yes
  apt:
    pkg:
      - npm
    
- name: Install pm2
  become: yes
  command:
    cmd: npm install pm2@latest -g
