- name: Create app directory
  command:
    cmd: mkdir ~/app
    
- name: copying artifact from local
  become: true 
  copy:
    src: /home/circleci/project/artifact.tar.gz
    dest: ~/app/artifact.tar.gz

- name: extract artifact
  become: yes
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: ~/app
    remote_src: no

- name: Install dependencies and start server
  become: yes
  command:
    cmd: cd ~/app && npm install && pm2 stop default && pm2 start npm -- start
