- name: Create app directory
  file:
    path: ~/app
    state: directory
    mode: '0755'

# - name: copy artifact from local 
#   copy:
#     src: /home/circleci/project/artifact.tar.gz
#     dest: ~/app/artifact.tar.gz

- name: extract artifact
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: ~/app
    remote_src: no

- name: Install dependencies and start server
  shell: |
    ls
    npm install
    pm2 stop default
    pm2 start npm -- start
  args:
    chdir: ~/app
  register: display_start_log

- debug:
    msg: "{{ display_start_log.stdout_lines }}"
